version: '3.8'

services:
  backend:
    build: .
    image: student-voice-backend:latest
    container_name: student-voice-backend
    command: server --console-address ":8080"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/student_voice
      SPRING_DATASOURCE_USERNAME: usre
      SPRING_DATASOURCE_PASSWORD: passw
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL: false
      SERVER_SERVLET_SESSION_TIMEOUT: 1h
      URFU_USER_USERNAME: username
      URFU_USER_PASSWORD: password
      URFU_AUTH_URL: https://sso.urfu.ru/adfs/OAuth2/authorize?resource=https://istudent.urfu.ru&type=web_server&client_id=https://istudent.urfu.ru&redirect_uri=https://istudent.urfu.ru/student/login/auth&response_type=code
      URFU_PAGE_URL: https://istudent.urfu.ru/
      MODEUS_URL: https://istudent.urfu.ru/s/modeus
      MODEUS_PERSONS_URL: https://urfu.modeus.org/schedule-calendar-v2/api/people/persons/search
      MODEUS_EVENTS_URL: https://urfu.modeus.org/schedule-calendar-v2/api/calendar/events/search
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: DEBUG
    volumes:
      - ./logs:/app/logs